use nota_next::{NotaDecode, NotaEncode, NotaSource};
use rkyv::{Archive, Deserialize as RkyvDeserialize, Serialize as RkyvSerialize};
use signal_introspect::{IntrospectionReply, PrototypeWitnessQuery as SignalPrototypeWitnessQuery};
use signal_persona::origin::EngineIdentifier;

#[derive(
    Archive, RkyvSerialize, RkyvDeserialize, NotaEncode, NotaDecode, Debug, Clone, PartialEq, Eq,
)]
pub struct PrototypeWitness {
    pub engine: EngineIdentifier,
}

impl PrototypeWitness {
    pub fn into_signal(self) -> SignalPrototypeWitnessQuery {
        SignalPrototypeWitnessQuery {
            engine: self.engine,
        }
    }
}

#[derive(
    Archive, RkyvSerialize, RkyvDeserialize, NotaEncode, NotaDecode, Debug, Clone, PartialEq, Eq,
)]
pub enum Input {
    PrototypeWitness(PrototypeWitness),
}

impl Input {
    pub fn from_nota(text: &str) -> crate::Result<Self> {
        NotaSource::new(text).parse().map_err(Into::into)
    }
}

#[derive(Archive, RkyvSerialize, RkyvDeserialize, Debug, Clone, PartialEq, Eq)]
pub struct Output {
    reply: IntrospectionReply,
}

impl Output {
    pub fn from_signal(reply: IntrospectionReply) -> Self {
        Self { reply }
    }

    /// Render the reply as NOTA by delegating to the typed payload's own
    /// `NotaEncode`. The `signal-introspect` reply enum is generated by
    /// `signal_channel!` and does not itself carry `NotaEncode`, so the
    /// projection dispatches on the closed variant set and wraps each payload's
    /// NOTA in its variant head.
    pub fn to_nota(&self) -> String {
        match &self.reply {
            IntrospectionReply::EngineSnapshot(snapshot) => {
                Self::wrap("EngineSnapshot", snapshot.to_nota())
            }
            IntrospectionReply::ComponentSnapshot(snapshot) => {
                Self::wrap("ComponentSnapshot", snapshot.to_nota())
            }
            IntrospectionReply::DeliveryTrace(trace) => {
                Self::wrap("DeliveryTrace", trace.to_nota())
            }
            IntrospectionReply::PrototypeWitness(witness) => {
                Self::wrap("PrototypeWitness", witness.to_nota())
            }
            IntrospectionReply::Unimplemented(unimplemented) => {
                Self::wrap("Unimplemented", unimplemented.to_nota())
            }
            IntrospectionReply::Denied(denied) => Self::wrap("Denied", denied.to_nota()),
        }
    }

    fn wrap(head: &str, payload: String) -> String {
        format!("({head} {payload})")
    }
}
