use dotos::{DotosDecode, DotosEncode, DotosSource};
use rkyv::{Archive, Deserialize as RkyvDeserialize, Serialize as RkyvSerialize};
use signal_introspect::{IntrospectionReply, PrototypeWitnessQuery as SignalPrototypeWitnessQuery};
use signal_persona::EngineIdentifier;

#[derive(
    Archive, RkyvSerialize, RkyvDeserialize, DotosEncode, DotosDecode, Debug, Clone, PartialEq, Eq,
)]
pub struct PrototypeWitness {
    pub engine: EngineIdentifier,
}

impl PrototypeWitness {
    pub fn into_signal(self) -> SignalPrototypeWitnessQuery {
        SignalPrototypeWitnessQuery {
            engine: self.engine,
        }
    }
}

#[derive(
    Archive, RkyvSerialize, RkyvDeserialize, DotosEncode, DotosDecode, Debug, Clone, PartialEq, Eq,
)]
pub enum Input {
    PrototypeWitness(PrototypeWitness),
}

impl Input {
    pub fn from_dotos(text: &str) -> crate::Result<Self> {
        DotosSource::new(text).parse().map_err(Into::into)
    }
}

#[derive(Archive, RkyvSerialize, RkyvDeserialize, Debug, Clone, PartialEq, Eq)]
pub struct Output {
    reply: IntrospectionReply,
}

impl Output {
    pub fn from_signal(reply: IntrospectionReply) -> Self {
        Self { reply }
    }

    /// Render the reply as DOTOS by delegating to the typed payload's own
    /// `DotosEncode`. The `signal-introspect` reply enum is generated by
    /// `signal_channel!` and does not itself carry `DotosEncode`, so the
    /// projection dispatches on the closed variant set and wraps each payload's
    /// DOTOS in its variant head.
    pub fn to_dotos(&self) -> String {
        match &self.reply {
            IntrospectionReply::EngineSnapshot(snapshot) => {
                Self::wrap("EngineSnapshot", snapshot.to_dotos())
            }
            IntrospectionReply::ComponentSnapshot(snapshot) => {
                Self::wrap("ComponentSnapshot", snapshot.to_dotos())
            }
            IntrospectionReply::DeliveryTrace(trace) => {
                Self::wrap("DeliveryTrace", trace.to_dotos())
            }
            IntrospectionReply::ComponentTrace(trace) => {
                Self::wrap("ComponentTrace", trace.to_dotos())
            }
            IntrospectionReply::PrototypeWitness(witness) => {
                Self::wrap("PrototypeWitness", witness.to_dotos())
            }
            IntrospectionReply::SystemEventAccepted(accepted) => {
                Self::wrap("SystemEventAccepted", accepted.to_dotos())
            }
            IntrospectionReply::SystemEvents(events) => {
                Self::wrap("SystemEvents", events.to_dotos())
            }
            IntrospectionReply::SystemEventsFlushed(flushed) => {
                Self::wrap("SystemEventsFlushed", flushed.to_dotos())
            }
            IntrospectionReply::Unimplemented(unimplemented) => {
                Self::wrap("Unimplemented", unimplemented.to_dotos())
            }
            IntrospectionReply::Denied(denied) => Self::wrap("Denied", denied.to_dotos()),
        }
    }

    fn wrap(head: &str, payload: String) -> String {
        format!("({head} {payload})")
    }
}
